# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:20
from __future__ import unicode_literals

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20170419_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default=banking.models.get_unique_number, max_length=8),
        ),
    ]
