# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20170419_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='_balance_currency',
            new_name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=10),
        ),
    ]
