# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20170419_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.Profile'),
        ),
    ]
